export const resources = [
  {
    id: 1,
    title: "Learning Sigleton Pattern",
    description: "I would like to learn singleton patter in JS!",
    link: "https://github.com/",
    image: "https://image.com",
    priority: 3,
    time: 120,
    active: true,
  },
  {
    id: 2,
    title: "Resource 2",
    description: "Resource 2 desc",
    link: "https://github.com/",
    image: "https://image.com",
    priority: 2,
    time: 60,
    active: false,
  },
  {
    id: 3,
    title: "Resource 3",
    description: "Resource 3 desc",
    link: "https://github.com/",
    image: "https://image.com",
    priority: 1,
    time: 180,
    active: false,
  },
];
